robot:
  name: "spot"
  mass: 34 # Kg
  end_effectors_frame_names:
    - "front_left_foot"
    - "front_right_foot"
    - "rear_left_foot"
    - "rear_right_foot"
  # bounding_ellipsoids:
  #   - semi_axes: [0.0, 0.0, 0.0] # base_link
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # FL_SHOULDER
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # FL_UPPER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # FL_LOWER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # FR_SHOULDER
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # FR_UPPER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # FR_LOWER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # HL_SHOULDER
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # HL_UPPER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # HL_LOWER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # HR_SHOULDER
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # HR_UPPER_LEG
  #     center: [0.0, 0.0, 0.0]
  #   - semi_axes: [0.0, 0.0, 0.0] # HR_LOWER_LEG
  #     center: [0.0, 0.0, 0.0]